######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 25 13:30:16 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += canvasgroup.h canvasview.h dialog.h tortuga.h
SOURCES += canvasgroup.cpp canvasview.cpp dialog.cpp main.cpp
