#############################################################################
# Makefile for building: canvas
# Generated by qmake (1.07a) (Qt 3.3.4) on: Sat Nov 25 13:30:27 2006
# Project:  canvas.pro
# Template: app
# Command: $(QMAKE) -o Makefile canvas.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt-3.3/mkspecs/default -I. -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = canvasgroup.h \
		canvasview.h \
		dialog.h \
		tortuga.h
SOURCES = canvasgroup.cpp \
		canvasview.cpp \
		dialog.cpp \
		main.cpp
OBJECTS = canvasgroup.o \
		canvasview.o \
		dialog.o \
		main.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_canvasview.cpp \
		moc_dialog.cpp
OBJMOC = moc_canvasview.o \
		moc_dialog.o
DIST	   = canvas.pro
QMAKE_TARGET = canvas
DESTDIR  = 
TARGET   = canvas

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: canvas.pro  /usr/lib/qt-3.3/mkspecs/default/qmake.conf /usr/lib/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile canvas.pro
qmake: 
	@$(QMAKE) -o Makefile canvas.pro

dist: 
	@mkdir -p .tmp/canvas && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/canvas/ && ( cd `dirname .tmp/canvas` && $(TAR) canvas.tar canvas && $(GZIP) canvas.tar ) && $(MOVE) `dirname .tmp/canvas`/canvas.tar.gz . && $(DEL_FILE) -r .tmp/canvas

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

canvasgroup.o: canvasgroup.cpp canvasgroup.h

canvasview.o: canvasview.cpp canvasview.h \
		canvasgroup.h

dialog.o: dialog.cpp canvasgroup.h \
		dialog.h \
		tortuga.h \
		canvasview.h

main.o: main.cpp dialog.h \
		canvasview.h \
		canvasgroup.h

moc_canvasview.o: moc_canvasview.cpp  canvasview.h canvasgroup.h

moc_dialog.o: moc_dialog.cpp  dialog.h canvasview.h \
		canvasgroup.h

moc_canvasview.cpp: $(MOC) canvasview.h
	$(MOC) canvasview.h -o moc_canvasview.cpp

moc_dialog.cpp: $(MOC) dialog.h
	$(MOC) dialog.h -o moc_dialog.cpp

####### Install

install:  

uninstall:  

